const root=document.documentElement;
const $$=(selector,scope=document)=>[...scope.querySelectorAll(selector)];
const $=(selector,scope=document)=>scope.querySelector(selector);
const cartKey='nbc-commerce-v03-cart';
const themeKey='nbc-commerce-theme';
const orderKey='nbc-commerce-v03-order';
const plans={individual:{label:'Individual',sites:'1 production site',price:49},team:{label:'Team',sites:'5 production sites',price:99},agency:{label:'Agency',sites:'25 production sites',price:179}};

function money(value){return `$${Number(value).toFixed(2)}`}
function readCart(){try{return JSON.parse(localStorage.getItem(cartKey))||null}catch{return null}}
function writeCart(cart){localStorage.setItem(cartKey,JSON.stringify(cart));syncCart(cart)}
function applyTheme(value){root.dataset.theme=value;const dark=value==='dark';$$('[data-theme-toggle]').forEach(button=>{button.setAttribute('aria-pressed',String(dark));button.setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme');button.textContent=dark?'☼ Light':'◐ Dark'});$('meta[name="theme-color"]')?.setAttribute('content',dark?'#171614':'#fff7e8')}
function initTheme(){const stored=localStorage.getItem(themeKey);const preferred=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';applyTheme(stored||preferred);$$('[data-theme-toggle]').forEach(button=>button.addEventListener('click',()=>{const next=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem(themeKey,next);applyTheme(next)}))}
function syncCart(cart=readCart()){$$('[data-cart-count]').forEach(node=>node.textContent=cart?'1':'0');if(!cart)return;const plan=plans[cart.plan]||plans.individual;$$('[data-cart-plan]').forEach(node=>node.textContent=plan.label);$$('[data-cart-sites]').forEach(node=>node.textContent=plan.sites);$$('[data-cart-price],[data-cart-subtotal],[data-cart-total]').forEach(node=>node.textContent=money(plan.price));$$('[data-cart-license]').forEach(node=>node.textContent=`${plan.label} · ${plan.sites}`)}
function initProduct(){const form=$('[data-product-config]');if(!form)return;const update=()=>{const selected=$('input[name="license"]:checked',form);const plan=plans[selected?.value]||plans.individual;$$('[data-live-plan]').forEach(node=>node.textContent=plan.label);$$('[data-live-price]').forEach(node=>node.textContent=`$${plan.price}`);$$('[data-live-sites]').forEach(node=>node.textContent=plan.sites)};form.addEventListener('change',update);update();$('[data-add-cart]')?.addEventListener('click',event=>{event.preventDefault();const selected=$('input[name="license"]:checked',form);const plan=selected?.value||'individual';writeCart({product:'soft',plan,quantity:1,addedAt:new Date().toISOString()});location.href=event.currentTarget.href})}
function initMedia(){$$('[data-media]').forEach(media=>{const tabs=$$('[data-media-tab]',media);const panels=$$('[data-media-panel]',media);const select=value=>{tabs.forEach(tab=>{const active=tab.dataset.mediaTab===value;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1});panels.forEach(panel=>panel.hidden=panel.dataset.mediaPanel!==value)};tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>select(tab.dataset.mediaTab));tab.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight'].includes(event.key))return;event.preventDefault();const next=(index+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].focus();select(tabs[next].dataset.mediaTab)})});select(tabs.find(tab=>tab.getAttribute('aria-selected')==='true')?.dataset.mediaTab||tabs[0]?.dataset.mediaTab)})}
function initCart(){const cart=readCart();const empty=$('[data-cart-empty]');const filled=$('[data-cart-filled]');if(empty&&filled){empty.hidden=Boolean(cart);filled.hidden=!cart}syncCart(cart);$('[data-clear-cart]')?.addEventListener('click',()=>{localStorage.removeItem(cartKey);location.reload()})}
function initInvoice(){const toggle=$('[data-invoice-toggle]');const fields=$('[data-invoice-fields]');if(!toggle||!fields)return;const sync=()=>{fields.hidden=!toggle.checked;toggle.setAttribute('aria-expanded',String(toggle.checked))};toggle.addEventListener('change',sync);sync()}
function initCheckoutState(){const state=new URLSearchParams(location.search).get('state')||'ready';$$('[data-checkout-state]').forEach(node=>node.hidden=node.dataset.checkoutState!==state);const submit=$('[data-checkout-submit]');if(submit){submit.disabled=state==='processing';submit.textContent=state==='processing'?'PROCESSING…':state==='failed'?'RETRY DEMO PAYMENT →':'PLACE DEMO ORDER →'}document.body.dataset.checkoutState=state}
function initCheckout(){syncCart();const cart=readCart();const gate=$('[data-checkout-gate]');if(gate&&!cart)gate.hidden=false;const form=$('[data-checkout-form]');form?.addEventListener('submit',event=>{event.preventDefault();const active=readCart()||{product:'soft',plan:'individual',quantity:1};const plan=plans[active.plan]||plans.individual;const order={id:`NBC-${Date.now().toString().slice(-6)}`,product:'NeoBrutal Soft',plan:active.plan,total:plan.price,createdAt:new Date().toISOString()};localStorage.setItem(orderKey,JSON.stringify(order));localStorage.removeItem(cartKey);location.href=form.action})}
function initOrder(){let order=null;try{order=JSON.parse(localStorage.getItem(orderKey))}catch{}if(!order)return;const plan=plans[order.plan]||plans.individual;$('[data-order-id]')&&( $('[data-order-id]').textContent=order.id );$('[data-order-plan]')&&( $('[data-order-plan]').textContent=plan.label );$('[data-order-total]')&&( $('[data-order-total]').textContent=money(order.total) )}
function initCopy(){$$('[data-copy]').forEach(button=>button.addEventListener('click',async()=>{const value=button.dataset.copy||'';try{await navigator.clipboard.writeText(value);button.textContent='COPIED ✓'}catch{button.textContent='COPY UNAVAILABLE'}setTimeout(()=>button.textContent='COPY',1200)}))}
function initCurrentNav(){const page=document.body.dataset.page;$$('[data-nav]').forEach(link=>{if(link.dataset.nav===page)link.setAttribute('aria-current','page')})}

initTheme();initCurrentNav();initProduct();initMedia();initCart();initInvoice();initCheckoutState();initCheckout();initOrder();initCopy();syncCart();
